stages:
  split:
    cmd: python src/data/split_data.py
    deps:
      - src/data/split_data.py
      - data/raw/raw.csv
    params:
      - split
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    params:
      - normalize
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
      - src/models/gridsearch.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    params:
      - gridsearch
    outs:
      - models/best_params.pkl

  training:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/best_params.pkl
    params:
      - model
    outs:
      - models/trained_model.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/trained_model.pkl
    outs:
      - data/predictions.csv
    metrics:
      - metrics/scores.json:
          cache: false